version: '3.3'
services:

  post_db:
    image: mongo:${MONGODB_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - reddit

  ui:
    image: ${USERNAME}/ui:${APP_UI_VERSION}
    ports:
      - ${APP_UI_PORT}:9292/tcp
    networks:
      - reddit-front

  post:
    image: ${USERNAME}/post:${APP_POST_VERSION}
    networks:
      - reddit
      - reddit-front

  comment:
    image: ${USERNAME}/comment:${APP_COMMENT_VERSION}
    networks:
      - reddit
      - reddit-front

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - reddit
      - reddit-front

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
  reddit-front:
